### ISSUE TITLE
Redfish.AllowableValues flagged as invalid property

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#106]
Redfish.AllowableValues annotations are flagged as invalid properties (not in schema). These should all be valid using the pattern properties.

See BootSourceOverrideTarget and BootSourceOverrideUefiTarget

**Comment by tomasg2012** [comment]
I've seen this come and go as a problem and I think it's a clarity issue more than a bug, but simultaneously it is a bug for another reason.  

Reviewing $metadata that you have passed to me, you don't have the Namespace "RedfishExtensions" aliased _specifically_ as "Redfish".  The annotation @Redfish.AllowableValues needs "Redfish" to be available, but since it isn't, it is unable to properly find the Schema needed to generate the annotation properly.  At least, that is how I've been told it needs to work.

The reason why this might still be considered a bug is that the Schema XML associated with the payload would normally have "Redfish" available, but annotations are strictly generated from $metadata, which makes it dependent.

**Comment by jautor** [comment]
Thanks @tomasg2012 I'll take the $metadata issue as a problem on my end, and let's add a specific error message for missing the Redfish Extensions (annotation) support to the tool as well.  I'll change this to an enhancement as the "bug" is on my end.

**Comment by billdodd** [comment]
Agree. It's clear that the RedfishExtensions needs to be aliased to 'Redfish'. Need to add an explicit check (probably in getReferenceFetails()) and issue an error if this is missing.
