### ISSUE TITLE
BIOS Attributes validation - many skipped

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#129]
A run of the Validator against a Bios resource results in about half of the Bios.Attributes getting validated (and PASS), and the remaining ones skipped as skipAdditional... Why would the validator skip some Attributes and test others?

**Comment by tomasg2012** [comment]
It might be tripping the logic in the validator which checks if something has been tested or not, could you provide an html and debug log?

**Comment by billdodd** [comment]
Samer,

I double-checked the output of a Bios validation on one of our systems and I'm not seeing any skipped attributes.

I think what you are seeing is that in the Bios section of the report, each Bios attribute gets 2 result entries (if there are DynamicPropertyPatterns). This is is an artifact of the additional DynamicPropertyPatterns checking that was recently added. The new checking happens in a different place than the existing attribute validation (where it checks for example that the attribute is expected).

I thought it would be confusing to try to merge the results of these 2 separate validations into one report line, so that's why there are 2 lines per attribute when there are DynamicPropertyPatterns.

But I can look into altering this behavior to merge results. Or something else that would be more clear?

But first I just want to confirm if there are really any missing attributes in your report. Here's what I see with a Bios validation. On the system I am testing, there are 287 Bios attributes. Near the top of the Bios section of the report, there are the DynamicPropertyPatterns results, the first few looking like this:

![screen shot 2017-12-07 at 1 58 34 pm](https://user-images.githubusercontent.com/3341721/33736212-6405dc5c-db57-11e7-9589-e3a9a3f66d8d.png)

And it continues on for all 287 attributes.

Then there are the original attribute validation results, the first few looking like this:

![screen shot 2017-12-07 at 1 59 09 pm](https://user-images.githubusercontent.com/3341721/33736272-9e141968-db57-11e7-9861-5556d8f5e892.png)

And likewise, that continues on for all 287 attributes.

Can you double-check your report and see if that matches your results? If not, and you are missing attributes in the report, could you please zip up and attach the 2 output files (ConformanceHtmlLog_*.html and ConformanceLog_*.txt)?

**Comment by mraineri** [comment]
@samerhaj any chance you can provide Bill with the logs so he can look at this further?

**Comment by samerhaj** [comment]
Sorry it took me so long.

I re-ran this on our latest FW and verified that:

- BIOS Attributes do indeed get validated
- For each BIOS attribute, two entries exist in the log. One that is validated, and one that is unverifiedComplexAdditional

pass: 422
passGet: 1
skipOem: 2
skipOptional: 1
unverifiedComplexAdditional: 138

So @billdodd comment above is correct.

Do we want to enhance the report to merge the results and avoid confusion,, or just close this issue?

**Comment by billdodd** [comment]
@samerhaj - thanks for replying.

It turns out that in my PR #167 from last Thursday I updated the logic so that if the Bios attributes do get validated it no longer creates an additional unverifiedComplexAdditional entry. So that should clear up the confusion.

**Comment by samerhaj** [comment]
awesome! I will go ahead and close this one. Thanks!
