### ISSUE TITLE
KeyError: 'uri'

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#14]
Can you explain what is wrong? Could it be my subdirectory with schema is not right name?

G:\_Redfish_git\Redfish-Service-Validator-Test\Redfish-Service-Validator>py -3 RedfishServiceValidator.py
RedfishServiceValidator Config details: (True, 'https://192.168.2.15', 'admin', 'metadata', False, False)

*** ServiceRoot, /redfish/v1
Starting new HTTPS connection (1): 192.168.2.15
C:\python35\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
@odata.context
@odata.id
@odata.type
@Redfish.Copyright
#ServiceRoot.1.0.0.ServiceRoot
Starting new HTTPS connection (1): 192.168.2.15
C:\python35\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 809, in <module>
    success, counts, results = validateURI('/redfish/v1', 'ServiceRoot')
  File "RedfishServiceValidator.py", line 703, in validateURI
    refDict = getReferenceDetails(SchemaSoup)
  File "RedfishServiceValidator.py", line 174, in getReferenceDetails
    refDict[item['namespace']] = (item['namespace'], ref['uri'])
  File "C:\python35\lib\site-packages\bs4\element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: 'uri'

[ComplianceLog_04_24_2017_191927.txt](https://github.com/DMTF/Redfish-Service-Validator/files/953457/ComplianceLog_04_24_2017_191927.txt)

**Comment by tomasg2012** [comment]
Actually, whatever service you are using seems to have returned something from "/redfish/v1/$metadata".  By default, the program will attempt to get schema from the service itself, it seems based on Line 19 it gave a response, but failed because the getReferences function.

The program itself assumes the schema grabbed makes sense.  However, the debug output doesn't show what it has from Line 19.  If you want to grab from schema XML files you placed in ./metadata, then you must enable LocalOnlyMode

**Comment by jbobzin-insyde** [comment]
Changing config.ini so LocalOnlyMode = True changed the error.
[ComplianceLog_04_24_2017_195021.txt](https://github.com/DMTF/Redfish-Service-Validator/files/953499/ComplianceLog_04_24_2017_195021.txt)


G:\_Redfish_git\Redfish-Service-Validator-Test\Redfish-Service-Validator>py -3 RedfishServiceValidator.py
RedfishServiceValidator Config details: (True, 'https://192.168.2.15', 'admin', 'metadata', False, True)

*** ServiceRoot, /redfish/v1
Starting new HTTPS connection (1): 192.168.2.15
C:\python35\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
@odata.context
@odata.id
@odata.type
@Redfish.Copyright
#ServiceRoot.1.0.0.ServiceRoot
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 728, in validateURI
    SchemaSoup, refDict, SchemaFullType, 'entitytype')
  File "RedfishServiceValidator.py", line 217, in getTypeDetails
    for element in innerschema.find_all(tagType, attrs={'name': SchemaType}):
AttributeError: 'NoneType' object has no attribute 'find_all'

Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 728, in validateURI
    SchemaSoup, refDict, SchemaFullType, 'entitytype')
  File "RedfishServiceValidator.py", line 217, in getTypeDetails
    for element in innerschema.find_all(tagType, attrs={'name': SchemaType}):
AttributeError: 'NoneType' object has no attribute 'find_all'

1
Counter({'exceptionGetType': 1, 'passGet': 1})
Validation has failed: 1 problems found

G:\_Redfish_git\Redfish-Service-Validator-Test\Redfish-Service-Validator>

**Comment by jbobzin-insyde** [comment]
here is the $metadata returned by the system under test
[metadata.txt](https://github.com/DMTF/Redfish-Service-Validator/files/953506/metadata.txt)

**Comment by tomasg2012** [comment]
Ah, I see the issues now.

For the first comment, the problem is that the newest DMTF schema does not match the old namespaces.  Ordinarily this is not a problem if you locally own the old schemas, but the new type format `"#ServiceRoot.v1_0_0.ServiceRoot"` does not match `"#ServiceRoot.1.0.0.ServiceRoot"`, and thus doesn't work.  This is something we've been discussing, and if your mockup or service is not up to date it might get past ServiceRoot but have issues down the line.

Now the metadata returned in the second comment has issues.  One being that I suspect the tags use the acronym `url` when default schema uses `uri`, the difference being the third letter.  Secondary to that, the namespace includes aren't accurate.  Refer to the XML with a search to find the namespace strings inside, eg "ServiceRoot.v1_0_0" or just "ServiceRoot"  Your service metadata must explicitly include the namespace of your JSON payload's type.

You current metadata refers to a previous version of schema such as http://redfish.dmtf.org/schemas/v1/ServiceRoot.xml , note the lack of v1 in the xml name.

**Comment by jbobzin-insyde** [comment]
Do you have a mockup with correct $metadata for 2016.3?
In general I have had trouble finding samples to study.

Thanks,
---Jeff

**Comment by mraineri** [comment]
It might be good to do key tests and fail if something doesn't exist; that way you can build a more understandable error rather than relying on an exception with a stack trace.

**Comment by tomasg2012** [comment]
I apologize as I keep editing my comments at the automatic emails may not be accurate.  But that is true, this is an exercise in service expectations that the program either should not have or should check for.

As it stands, $metadata itself is dependent on the service, but as an expectation, the root document "/redfish/v1/$metadata" returns something like this:

[metadataNow.txt](https://github.com/DMTF/Redfish-Service-Validator/files/953555/metadataNow.txt)

And should be similar in exceptions to the namespaces and file destinations, which can be hosted on the service via a uri and not via a url (as in sans http://etc).

**Comment by jbobzin-insyde** [comment]
changing the config.ini setting to LocalOnlyMode = True changed the error.
[ComplianceLog_04_24_2017_195021.txt](https://github.com/DMTF/Redfish-Service-Validator/files/953497/ComplianceLog_04_24_2017_195021.txt)

**Comment by jbobzin-insyde** [comment]
Problem in the test system

**Comment by tomasg2012** [comment]
http://www.dmtf.org/standards/redfish

If you wish to try the appropriate 1.0.0 schema, it is located on this page as DSP8010.  Then you would have to put those in your local XML, they might need to be renamed with _v1 in the title.   I don't have access to a 1.0.0 service.  It should be able to work with 1.0.0 services to some degree.

There are also mockups if you still need reference material, as the latest DSP2043 zip file.

**Comment by jbobzin-insyde** [comment]
I did some patching today in Redfish implementation today. Will test tomorrow.
Might take a couple days to avoid blowing up your program.
Our implementation is targeting 2016.3 release.
