### ISSUE TITLE
False error for null HttpHeaders in EventDestination

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Validator#196]
According to the description of "HttpHeaders" in https://redfish.dmtf.org/schemas/EventDestination.v1_2_2.json: "This object will be null on a GET".

But Redfish-Service-Validator flags this as an error with "ERROR - HttpHeaders: Value of Collection property is null but Collections cannot be null, only their entries"

**Comment by mraineri** [comment]
Since there are shipping implementations with null being returned (and it's called out that way in the schema long description), we'll need to add a workaround so that the service validator ignores this for HttpHeaders within EventDestination.

**Comment by mraineri** [comment]
Since 2019.1 is public now, the group decided that in order to preserve backwards compatibility, we need to continue allowing for the property to be "null", even though this does violate normal CSDL semantics. We will need to add a special case in the tool for handling this property to allow for the value to be "null".
