### ISSUE TITLE
badNamespaceInclude for RedfishError

### ISSUE THREAD

**Issue by cactusjiang** [DMTF/Redfish-Service-Validator#304]
We got the following error after adding RedfishError_v1.xml and redfish-error.v1_0_0.json.
```
ERROR - The following namespaces included in $metadata could not be found in the referenced schema URI:
Namespace redfish-error.v1_0_0 not found in schema /redfish/v1/metadata/RedfishError_v1.xml
Namespace redfish-error not found in schema /redfish/v1/metadata/RedfishError_v1.xml
```
It seems the dmtf tool does not have the knowledge to map RedfishError_v1.xml and redfish-error.v1_0_0.json because the term "redfish-error" is not defined in RedfishError_v1.xml.

**Comment by billdodd** [comment]
The $metadata document should point to CSDL schema files and reference the needed namespaces defined in those CSDL files. The namespace defined in RedfishError_v1.xml is RedfishError.v1_0_0.

I don't know why the JSON schema file for RedfishError is named redfish-error.v1_0_0.json. But as far as I know, the service's $metadata and the Redfish-Service-Validator should be using the namespaces as defined in the CSDL.

@cactusjiang @mraineri - If my understanding is not correct, can you clarify?

**Comment by mraineri** [comment]
Redfish Error shouldn't be included in $metadata since OData already defines the error structure. The only reason we have a schema file for it is for clarity in the definition (so you don't need to go through the OData specs for the definition).

The file is constructed by hand since these are not actually resources and do not get used by any resources.

**Comment by cactusjiang** [comment]
@mraineri Got it. Thanks for the clarification. We will remove the RedfishError from $metadata.
