### ISSUE TITLE
Getting Unexpected Error on Boot.BootSourceOverrideMode

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#32]
@odata.type is #ComputerSystem.v1_3_0.ComputerSystem
But getting this error 
ERROR - Boot.BootSourceOverrideMode: Appears to be an extra property (check inheritance or casing?)
This is property added in v1.1.0
Above this in log is
INFO - ComputerSystem.v1_0_0.Boot:UefiTargetBootSourceOverride
Is it possible the tool is using Boot from 1.0.0 schema instead of 1.3.0?
This test is done with schema from dmtf.org
[ComplianceLog_05_26_2017_102019.zip](https://github.com/DMTF/Redfish-Service-Validator/files/1032247/ComplianceLog_05_26_2017_102019.zip)

**Comment by tomasg2012** [comment]
The change that makes this act additional is based on a statement by M
Raineri, that Annotations in any Resource or Object must be referenced in
the Service $metadata xml and NOT the Resource's schema XML.

This would require RedfishExtension with an Alias of Redfish to exist as a
reference in the doc returned by /redfish/v1/$metadata.  If you're in
LocalOnlyMode, $metadata is never polled and instead looks for
".../metadata.xml" but I might change that or converge that with
ServiceMode.

If you try ServiceMode instead of LocalOnlyMode, it will only GET from URIs
that exist within the service and not outgoing elsewhere, such as DMTF
refs.  This should grab $metadata properly.


On May 26, 2017 10:03 AM, "jbobzin-insyde" <notifications@github.com> wrote:

@odata.type is #ComputerSystem.v1_3_0.ComputerSystem
But getting this error
ERROR - Boot.BootSourceOverrideMode: Appears to be an extra property (check
inheritance or casing?)
This is property added in v1.1.0
Above this in log is
INFO - ComputerSystem.v1_0_0.Boot:UefiTargetBootSourceOverride
Is it possible the tool is using Boot from 1.0.0 schema instead of 1.3.0?
This test is done with schema from dmtf.org
ComplianceLog_05_26_2017_102019.zip
<https://github.com/DMTF/Redfish-Service-Validator/files/1032247/ComplianceLog_05_26_2017_102019.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DMTF/Redfish-Service-Validator/issues/32>, or mute the
thread

**Comment by jbobzin-insyde** [comment]
I want to assure you the test leading to this issue was done with redfish.dmtf.org, because LocalOnlyMode and ServiceMode are both set to false in config.ini.

Also, $metadata includes this
`<edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
<edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
</edmx:Reference>`

**Comment by tomasg2012** [comment]
Sorry, I read the wrong property in this context and answered you incorrectly, let me look into this property and give you a more accurate response.

**Comment by tomasg2012** [comment]
After I misunderstood the question, I realized this is a completely different issue of understanding how inheritance works between types.  There is a higher version of Boot "v1_1_0" in the Namespace you specified, but because there is no such Property "Boot" in that Namespace that has a BaseType of Boot inside of "v1_1_0", such as "ComputerSystem.v1_1_0.Boot", instead it is only aware of the Property with BaseType "ComputerSystem.v1_0_0.Boot" within that Namespace.

Due to the navigation issue present in the Interop tool, I will be constructing a much more robust tree that should have the ability to alleviate this issue through parental checking.

**Comment by jbobzin-insyde** [comment]
How are you doing with this one?  I am also seeing this on
Chassis.v1_2_0.Links.Storage
I get
  `ERROR - Links.Storage: Appears to be an extra property (check inheritance or casing?)`
which I think is same failure as System.v1_1_0.Boot.BootSourceOverrideMode

**Comment by tomasg2012** [comment]
Raineri brought up an interesting spec definition that was finalized just this May that Complex objects and Resources should contain an @odata.type, such that it would nullify this issue.  However, considering backwards compatibility is necessary, the program should still attempt to check for a higher type and inherit from it.  The issue is still under work.

**Comment by tomasg2012** [comment]
This should be fixed in the new pull, which collaborates the highest type available and polls for ComplexType changes (as of now, just Complex).

**Comment by jbobzin-insyde** [comment]
The false "extra property error"  with ComputerSystem.Boot.BootSourceOverrideMode and Chassis.v1_2_0.Links.Storage are still seen after the recent pull.

**Comment by tomasg2012** [comment]
I apologize, seems that I made the mistake in assuming Schemas, as described in Schema tags in a CSDL file, have a "BaseType".  However, it is the EntityType inside the Schemas that have BaseTypes that point to earlier EntityTypes, the current method doesn't actually check types lower than the current one.

It's a simple fix, but I'm not sure which of two approaches is more accurate:
1. List all Schema in the CSDL file and check every version at/below the current Namespace.
2. Check the current Namespace, and use the BaseType of the Entity inside the Namespace to traverse to a lower type.

**Comment by mraineri** [comment]
Option 2 should be the more appropriate one. With the way we version our namespaces, it's the reliable method.

**Comment by tomasg2012** [comment]
This should be in the branch 'enhancements-06-12' now.  If you would like to give it a try before Thursday, it would be appreciated, sorry for the oversight.

**Comment by jbobzin-insyde** [comment]
fixed in the latest branch
