### ISSUE TITLE
"RAIDType"  is not defined in DSP8010_2019.1 Volume_v1.xml schema

### ISSUE THREAD

**Issue by yinchilee** [DMTF/Redfish-Service-Validator#360]
Hi,

We use the latest tool to validate service and get "RAIDType" error for Storage.

Error message:
![storage](https://user-images.githubusercontent.com/55127828/71789876-766fec80-3068-11ea-8a54-75998d29760e.jpg)

I use DSP8010_2019.1 schema but "RAIDType" is not defined
in Volume_v1.xml 

DSP8010_2019.3 Volume_v1.xml  schema has Defined "RAIDType".
![raidtype](https://user-images.githubusercontent.com/55127828/71789949-d6ff2980-3068-11ea-92fb-c1dcc9fa43fe.jpg)

**Comment by mraineri** [comment]
The DMTF passed off ownership of the Volume schema to SNIA several years ago. Since then SNIA has owned its publication. As of the second half of 2019, we have started republishing the latest SNIA version of Volume in the 8010 bundle, but ultimately Volume should be downloaded from the Swordfish schema repo here: http://redfish.dmtf.org/schemas/swordfish/v1/

**Comment by yinchilee** [comment]
@mraineri  Thank you for your explanation.
