### ISSUE TITLE
Capabilities restrictions checking 

### ISSUE THREAD

**Issue by J2Hilland** [DMTF/Redfish-Service-Validator#419]
The schema defines capabilities restrictions (updatable, insertable, deletable) but it appears that these aren't being checked as some implementations are coming back with odd values in the Allow header.  For instance, singleton resources with POST.  It seems that this should be checked and flagged (warning for now, at the very least).

**Comment by mraineri** [comment]
Some of those should definitely be problematic and flagged, but something like PATCH on a singleton resource might be difficult to test since the OEM object could be modifiable in a normally read-only resource. Maybe simply the presence of "Oem" is good enough to allow for "PATCH" in the Allow header (at least until we come up with a better method to test for this).

**Comment by mraineri** [comment]
Latest PR adds this support
