### ISSUE TITLE
How does it handle the error that a redfish URI does not respond？

### ISSUE THREAD

**Issue by haitaoso** [DMTF/Redfish-Service-Validator#443]
Wait all the time？ Mark a timeout error then continue the verification?
In the old version 1.4.1, looks like it marks a timeout error.
But in the latest version:2.0.7, it waits all the time. 
I download source codes and view them, the timeout variable is defined in the "callResourceURI" function, but it doesn't seem to be used. Is this an error？

**Comment by mraineri** [comment]
Since 2.0.0, it uses the python-redfish-library for the lower level calls. Ultimately the timeout is performed at that level, From looking at the library, it does perform quite a few retries, and I assume the calls it makes uses fairly common HTTP timeouts (perhaps on the order or 30 seconds), so that could seem like quite a long time if there's a true timeout condition.

I think it might be worth looking at this further from the perspective of the python-redfish-library, since I've noticed similar cases with other tools leveraging the library.

**Comment by haitaoso** [comment]
Thanks for your answer.

I noticed that the python-redfish-library supports timeout settings when instantiating the redfish client by passing in the timeout parameter.
Maybe we can set timeout when instantiating the redfish client.
```python
# common/traverse.py  line:54
        self.context = rf.redfish_client( base_url = rhost, username = user, password = passwd )

        # self.context = rf.redfish_client( base_url = rhost, username = user, password = passwd, timeout = self.config['timeout'])
```

**Comment by mraineri** [comment]
I think that's a reasonable addition to the tool.

Have you been able to try it yourself with the system you're testing to see if that helps your issue?

**Comment by haitaoso** [comment]
Yes, I have tried it with my system. It taken effect.
