### ISSUE TITLE
failAllowHeader error is reported in Certificate

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#479]
We get the below error:
1 failAllowHeader errors in /redfish/v1/Managers/1/NetworkProtocol/HTTPS/Certificates/1

But there are Actions designed in the Certificate so it should allow to have the header `Allow: POST` .

Here is the debug log:
[Certificate_debug.log](https://github.com/DMTF/Redfish-Service-Validator/files/8359413/Certificate_debug.log)

**Comment by mraineri** [comment]
The Allow header shouldn't show methods for actions since the URI to invoke the action is different than the resource URI. By showing POST in the Allow header for "/redfish/v1/Managers/1/NetworkProtocol/HTTPS/Certificates/1", this tells a client that POST to "/redfish/v1/Managers/1/NetworkProtocol/HTTPS/Certificates/1" is valid, which is not correct; a client can never POST to that URI.

**Comment by JojoWu19** [comment]
@mraineri , you are right, thank you.
Close this.
