### ISSUE TITLE
ServiceRoot throws warning on checkPayloadConformance

### ISSUE THREAD

**Issue by aahmed-2** [DMTF/Redfish-Service-Validator#488]
Call path:
RedfishServiceValidator.py:172 - validateURITree(currentService, '/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
validateResource.py:284           - validateSingleURI(service, URI, uriName, expectedType, expectedJson, parent)
validateResource.py:91              - checkPayloadConformance(me['payload'], URI)
common/helper.py:157               - my_logger.warning("{} {}: Expected @odata.id to match URI link {}".format(uri, key, decoded[key]))

In helper.py, checkPayloadConformance, comparison between "/redfish/v1/" and "/redfish/v1" fails and results in 157 being triggered.

**Comment by jautor** [comment]
That appears to be a proper warning.  While you may redirect or otherwise use "identical" payload, the definition of @odata.id wants that value to match the URI requested.  So a warning (not a failure) that the value "/redfish/v1" doesn't match the requested "/redfish/v1/" (or vice versa) is expected.
