### ISSUE TITLE
About the error respond "not match object IDs of resource chain"

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Service-Validator#531]
Hi,

Some errors indicate "URI {} does not match object IDs of resource chain".
As far as I know, the value of the property "ID" must be the same as the word after the last slash in the link of "@odata.id", what other specifications must be met to avoid such errors from happening?
Take a screenshot as an example：
![1](https://user-images.githubusercontent.com/85208691/217172642-c1a841d2-78b4-4197-a6d8-2a22bbac5fde.JPG)
![2](https://user-images.githubusercontent.com/85208691/217172981-6ae72f10-a43a-4e3b-9e4a-f5e2ebed43e3.JPG)

In the URI of the upper layer, the "Members" also lists the correct link.
![3](https://user-images.githubusercontent.com/85208691/217173658-e9eb4e05-ba3f-4813-be78-2669d35b01e1.JPG)

Thanks,
Felix

**Comment by tomasg2012** [comment]
The Ids are only checked in the Resource itself, so the bottom screenshot will pass.

However, not sure about the top image.  It checks every resource Id in the path.  Does your `/redfish/v1/Systems/Self` pass as well?  

After looking into the Schema for USBController, the issue seems to be how the tool interprets the URL.  It is written with `{ControllerId}` instead of `{USBControllerId}`. This is a tool/schema error so it should not be changed on your end.

**Comment by mraineri** [comment]
@tomasg2012 let's check two things with this:

1) Ensure there's no dependency with parent resources; so, even if "/redfish/v1/Systems/Self" is not correct, that should not impact child resources like with this USB controller resource.
2) Don't rely on the names of the tokens inside of the curly braces or perform matching with the resource name since the token names aren't required to match the resource name; simply the presence of the curly braces is sufficient.
