### ISSUE TITLE
"Tree" usage for testing every links

### ISSUE THREAD

**Issue by Againxarcher** [DMTF/Redfish-Service-Validator#567]
Hi,

I tried to give "tree" for payload argument to run the validator.
![image](https://github.com/DMTF/Redfish-Service-Validator/assets/147082751/8c54cfc2-d161-4f17-b9f1-89290bc4538c)

So it will be test all links under "/redfish/v1/Systems/Self/NetworkInterfaces".
![image](https://github.com/DMTF/Redfish-Service-Validator/assets/147082751/061f4658-5591-4d41-a517-391d6ade37b3)
![image](https://github.com/DMTF/Redfish-Service-Validator/assets/147082751/2141ec10-3aff-4d6a-934a-b26f3763c121)

But I observed the next link under "/redfish/v1/Systems/Self/NetworkInterfaces/DevType7_NIC0" didn't be run.
![image](https://github.com/DMTF/Redfish-Service-Validator/assets/147082751/8d55bd4e-24ab-411e-907b-68539bcf313f)

Shall it be run or this is normally behavior?

Here is the attached report for reference.
[1024.zip](https://github.com/DMTF/Redfish-Service-Validator/files/13175596/1024.zip)

**Comment by mraineri** [comment]
Yes, this is correct behavior. Because that link is inside of the "Links" object, it's not considered subordinate to the resource, and therefore is not considered part of the tree.

In most URIs for Redfish, you can visualize this just from the URI itself. For example, everything starting with "/redfish/v1/Chassis/1/PowerSubsystem" would be considered subordinate to Chassis 1's PowerSubsystem resource and is therefore in the tree. However, the advanced comm device model has some cross linking for ease of expansion, such as how the "Ports" collection beneath a NetworkInterface resource contains members within the Chassis URI pattern. However, since "Ports" is not inside of "Links", it's treated as part of the resource tree, and is then tested.

**Comment by Againxarcher** [comment]
Got it, Thanks.
