### ISSUE TITLE
Runtime check for incompatible bs4 version?

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Service-Validator#60]
During the Plugfest, the beautifulsoup4 version issue hit a few people. It's hard for a user to diagnose this problem.

Is it possible to do an explicit check for the incompatible version and issue a helpful warning?
Would also apply to Reference Checker, Interop Validator and maybe other tools.

**Comment by tomasg2012** [comment]
Ah, can do.  The Reference Checker specifically doesn't specify the version
either... you should be able to do

pip3 install -r requirements.txt

on the Service Validator just once... but if you're using virtualenv
between tools then it might not be the case.

On Jul 25, 2017 1:27 PM, "Bill Dodd" <notifications@github.com> wrote:

During the Plugfest, the beautifulsoup4 version issue hit a few people.
It's hard for a user to diagnose this problem.

Is it possible to do an explicit check for the incompatible version and
issue a helpful warning?
Would also apply to Reference Checker, Interop Validator and maybe other
tools.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DMTF/Redfish-Service-Validator/issues/60>, or mute the
thread

**Comment by billdodd** [comment]
Results of a short search for how to do this:

Can get the version of the currently installed bs4 easily: `bs4.__version__`

Comparing versions is a little tricky. This SO post seems pretty comprehensive:

https://stackoverflow.com/questions/11887762/compare-version-strings-in-python

**Comment by mraineri** [comment]
Fixed in latest PR
