### ISSUE TITLE
Validator should use latest errata schemas

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#68]
When validating payloads against schema, the validator should ignore the errata version listed by the Service and always use the latest errata schema for that major.minor version.  

Schema bugs can (and do) cause false validation failures because the Service was built with previous schema releases.  The Service cannot be required to be updated to deal with known-and-fixed schema bugs.

For example, a Service resource specifying "v1.0.0" of ComputerSystem should be validated against "v1.0.5", the latest errata schema for that minor version.

**Comment by jbobzin-insyde** [comment]
I would like to discuss making this higher prioirty

**Comment by tomasg2012** [comment]
This should be implemented howso, any type that is described as `v1_0_*`, where asterisk is a number, should be interpreted as the highest possible version/namespace that exist in a schema?  

if say, v1_0_9 exists as the highest schema, and anything ( @odata.type, "BaseType=" ) should refer to v1_0_9?

@jbobzin-insyde , and anyone else, my issue here is does this refer only to @odata.type in payloads or to internal XML affairs, since "Resource.v1_0_0" as a BaseType exists in XML?  I just want to make sure there's not any confusion/implications about the type chain that should or shouldn't be followed.  It's a fairly simple change to accomodate for "Resource.v1_0_0", it's the only BaseType that crosses to another XML, so this is not much of an issue if it's the only exception.

**Comment by jautor** [comment]
@tomasg2012 this should apply only to the odata.type in the payloads...

**Comment by mraineri** [comment]
Closing; errata changes will be reflected back in the original namespace, since you can't redefine or extend property definitions. Errata namespaces just contain a trivial stub of an entity, and a note as to why the namespace was added.
