### ISSUE TITLE
Timeout 30 Minutes?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#74]
Not sure where you got the constant here

`self.timeout, self.tick = timedelta(minutes=30), datetime.now()`

And therefore Not sure I understand the motivation of isSessionOld()

**Comment by tomasg2012** [comment]
This is a temporary functionality to determine with a Session is timed out on a service, which I believe is a value you can find... I actually don't know the where to find the expected timeout for a Session between requests.

Since the code itself is constantly making requests, the likelihood of a session timing out would be zero.  The isSessionOld() code is not necessarily complete (was really quick on writing it) and is there in case it might be finished in the future.  All it will do is just print a string.

**Comment by jbobzin-insyde** [comment]
Ok. I just saw that the code and it did not make sense.
